# Generated by Django 5.2.1 on 2025-05-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_image_product_cat_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_obj',
            field=models.ManyToManyField(blank=True, null=True, to='products.category'),
        ),
    ]
